version: '3.3'

services:
  jupyter:
    build:
      context: .
    ports:
      - "8888:8888"  # Porta padrão da interface web do Jupyter Notebook
        #      - "4040:4040"  # Porta padrão da interface web do Spark
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data
      - ./config:/home/jovyan/.jupyter

# Definindo as redes que serão usadas pelos serviços.
    networks:
      - mybridge # Nome da rede que será usada.

# Configuração das redes que serão usadas no docker-compose.
networks:
  mybridge: # Nome da rede.
    external: # Indica que a rede é externa e já foi criada anteriormente.
      name: mybridge # Nome da rede externa que será usada.

volumes:
  notebooks:
  data:
  config:          
